dist: xenial
language: python
jobs:
  include:
  - python: "3.7"
    env: SUBPROCESS32=latest
addons:
  apt:
    packages:
    - djvulibre-bin
    - docbook-xml
    - docbook-xsl
    - libdjvulibre-dev
    - libicu-dev
    - libxml2-utils
    - xsltproc
cache: pip
before_install:
- cython="cython${CYTHON:+==$CYTHON}"
- pydjvu="python-djvulibre${PYDJVU:+==$PYDJVU}"
- lxml="lxml${LXML:+==$LXML}"
- if [[ -z $SUBPROCESS32 ]]; then
    if_subprocess32=:;
  else
    subprocess32="subprocess32==$SUBPROCESS32";
    subprocess32="${subprocess32%==latest}";
  fi
- pyicu="pyicu${PYICU:+==$PYICU}"
- html5lib="html5lib${HTML5LIB:+==$HTML5LIB}"
- pillow="pillow${PILLOW:+==$PILLOW}"
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
install:
- pip install --verbose $cython
- pip install --verbose $pydjvu
- $if_subprocess32 pip install --verbose $subprocess32
- pip install --verbose $lxml
- pip install --verbose $pyicu
- pip install --upgrade setuptools
- pip install $html5lib
- pip install --verbose $pillow
- pip install pydiatra
- pip install $pyflakes
- pip install docutils
script:
- make test
- py2diatra .
- private/run-pyflakes
- make -C doc check
- make -C doc all
- make install PREFIX=$HOME/.local
- cd /
- djvu2hocr --version
- hocr2djvused --version
- ocrodjvu --version
- export MANPATH="$HOME/.local/share/man" MANWIDTH=80
- man 1 ocrodjvu | grep -A 10 -w OCRODJVU
- man 1 djvu2hocr | grep -A 10 -w DJVU2HOCR
- man 1 hocr2djvused | grep -A 10 -w HOCR2DJVUSED
- curl -fsS https://pypi.org/simple/ocrodjvu/; [ $? -eq 22 ]

# vim:ts=2 sts=2 sw=2 et
